[phases.setup]
nixPkgs = ["php82", "nodejs_20"]

[phases.install]
cmds = ["npm ci", "composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["npm run build", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
